export const users = [
  createUser('StroShow6', 432),
  createUser('Joe', 2916),
  createUser('HUGEWall', 45447),
  createUser('PhilDaThrill', 2489),
  createUser('SavageAndrew', 1619),
  createUser('BigBallerZo', 23),
  createUser('Chandler1', 8),
  createUser('KawhiLnrd', 43),
  createUser('Leafs4Cup', 17473),
  createUser('RossGeller', 8328),
  createUser('MasterChief', 33),
  createUser('DubasGM', 3470),
  createUser('JogLog69 ', 823),
  createUser('Yeeeeeeet', 3827),
  createUser('memeGod', 328),
]

export const questions = [
  createQuestion({
    user: 7,
    title: 'How to undo the most recent commits in Git?',
    body: 'I committed the wrong files to Git, but have not pushed yet. How can I undo?',
    score: 2,
    tags: [12],
    comments: [0, 9, 10],
    answers: [0],
  }),
    createQuestion({
    user: 10,
    title: 'Remove a particular element from an array in JavaScript?',
    body: 'Is there a simple way to remove a specific element from an array or integers?',
    score: 16,
    tags: [9],
    comments: [1, 2, 7],
    answers: [1, 3],
  }),
  createQuestion({
    user: 9,
    title: 'Why did my program break?',
    body: 'I keep getting a segment fault when I try to run my code.',
    score: -51,
    comments: [2,3],
    tags: [1, 19],
  }),
  createQuestion({
    user: 5,
    title: 'BigO for inserting values to the end of a linked list',
    body: 'Exactly what the title says, I need help figuring out the BigO.',
    score: 39,
    tags: [3, 9],
    comments: [1, 7],
    answers: [4, 5],
  }),
  createQuestion({
    user: 13,
    title: 'Git + LaTeX workflow',
    body: 'I need to keep all the files synchronized between my work computer and laptop.',
    score: 13,
    tags: [12, 13],
    comments: [1],
  }),
  createQuestion({
    user: 2,
    title: 'Public vs. Protected vs. Private in Java',
    body: 'What is the difference between public, protected, and private in Java?',
    score: 6,
    tags: [3, 9],
    comments: [8, 1],
    answers: [5],
  }),
  createQuestion({
    user: 0,
    title: 'Close/hide the Android Soft Keyboard',
    body: 'After writing in the edit field and clicking on the button, I want to hide the virtual keyboard.',
    score: 19,
    tags: [7],
    comments: [0, 6],
    answers: [6],
  }),
  createQuestion({
    user: 8,
    title: 'API calls failing after updating Windows',
    body: 'I\'ve been sporadically encountering errors with all of my API calls',
    score: 10,
    tags: [3, 9],
    comments: [4, 6],
    answers: [7],
  }),
  createQuestion({
    user: 14,
    title: 'Can comments be used in JSON?',
    body: 'Can I use comments inside a JSON file? If so, how?',
    score: 34,
    tags: [22],
    comments: [9, 10],
    answers: [8, 9],
  }),
  createQuestion({
    user: 6,
    title: 'Why does HTML think “chucknorris” is a colour?',
    body: 'How come certain strings produce colors when entered as background colours in HTML? What\'s going on?',
    score: 1,
    tags: [3],
    comments: [8, 7],
    answers: [10],
  }),
  createQuestion({
    user: 3,
    title: 'Javascript comparisons',
    body: 'Which equals operator (== vs ===) should be used in JavaScript comparisons?',
    score: 2,
    tags: [9],
    comments: [3],
    answers: [11, 12],
  }),
  createQuestion({
    user: 12,
    title: 'Why is it faster to process a sorted array than an unsorted array?',
    body: 'For some strange reason, sorting the data miraculously makes code almost four times faster',
    score: 47,
    tags: [1, 2],
  }),
  createQuestion({
    user: 7,
    title: 'Read .MAT files in Python',
    body: 'Does anyone have successful experience reading binary Matlab .mat files in Python?',
    score: 31,
    tags: [4, 20],
    comments: [0, 1],
    answers: [13,14],
  }),
  createQuestion({
    user: 14,
    title: 'SELECT FROM WHERE query not returning the right values.',
    body: 'I am running a SQL query but I can\'t seem to pull the right values from the database.',
    comments: [2,3],
    score: -3,
    tags: [5],
    comments: [2,3],
  }),
  createQuestion({
    user: 11,
    title: 'How do I copy folder with files to another folder in Linux?',
    body: 'Command cp -r doesn\'t copy files in the folder.',
    score: 0,
    tags: [14],
    comments: [4,5,8],
    answers: [15],
  }),
]

export const comments = [
  createComment({user: 1, body: 'I\'m having the same issue.'}),
  createComment({user: 2, body: 'This a great question.'}),
  createComment({user: 3, body: 'You need to post a snippet of your code.'}),
  createComment({user: 4, body: 'We can\'t do your homework for you.'}),
  createComment({user: 5, body: 'Linux is the master race.'}),
  createComment({user: 6, body: 'That\'s odd, seems to be working for me.'}),
  createComment({user: 7, body: 'Did you try turning it off and back on again?'}),
  createComment({user: 8, body: 'They asked me this question during my interview.'}),
  createComment({user: 9, body: 'This question might be a duplicate.'}),
  createComment({user: 10, body: 'This is a dumb question.'}),
  createComment({user: 11, body: 'There is no such thing as stupid questions.'}),
]

export const answers = [
  createAnswer({user: 2, body: 'You want to drop the commit, you do the following: git reset --hard HEAD~1'}),
  createAnswer({user: 6, body: 'Find the index of the array element you want to remove, then remove that index with splice.'}),
  createAnswer({user: 4, body: "To remove an element of an array at an index i: array.splice(i, 1);"}),
  createAnswer({user: 10, body: 'The insertion itself is O(1), but getting there is O(n), so the whole process is O(n)'}),
  createAnswer({user: 9, body: 'O(n). Source: Algorithms textbook by Robert Sedgewick'}),
  createAnswer({user: 11, body: 'Private: only the class in which it is declared can see it, Protected: can be seen by subclasses, Public: everyone can see it.'}),
  createAnswer({user: 12, body: 'You can force Android to hide the virtual keyboard using the InputMethodManager, calling hideSoftInputFromWindow, passing in the token of the window containing your focused view.'}),
  createAnswer({user: 3, body: 'Looks like you\'re  going to have to reinstall Windows.'}),
  createAnswer({user: 7, body: 'No: the JSON should all be data, and if you include a comment, then it will be data too.'}),
  createAnswer({user: 0, body: 'No, comments of the form //… or /*…*/ are not allowed in JSON.'}),
  createAnswer({user: 9, body: 'Most browsers will ignore any non-hex values in your color string, substituting non-hex digits with zeros.'}),
  createAnswer({user: 8, body: 'The identity (===) operator behaves identically to the equality (==) operator except no type conversion is done, and the types must be the same to be considered equal.'}),
  createAnswer({user: 4, body: 'If in doubt, read the specification!'}),
  createAnswer({user: 2, body: 'There is a nice package called mat4py which can easily be installed using: pip install mat4py'}),
  createAnswer({user: 11, body: 'Did you use the import statement: import scipy.io?'}),
  createAnswer({user: 13, body: 'use: $ cp -R SRCFOLDER DESTFOLDER'}),
  createAnswer({user: 13, body: 'use: $ cp -R SRCFOLDER DESTFOLDER'}),
]

export const tags = [
  'C#',
  'C++',
  'Java',
  'HTML',
  'Python',
  'SQL',
  'API',
  'Android',
  'jQuery',
  'JavaScript',
  'CSS',
  'Regex',
  'Git',
  'LaTeX',
  'Linux',
  'PHP',
  'Angular.js',
  'Node.js',
  'React.js',
  'C',
  'MATLAB',
  'ASP.NET',
  'JSON',
  'Database',
  'VBA',
  'AWS',
  'Ruby',
  'Selenium',
  'Swift',
]

function createUser(name, score) {
  return {name, score}
}

function createQuestion({
  user,
  title,
  body,
  tags,
  score = 0,
  answers = [],
  comments = [],
}) {
  return {user, title, body, tags, score, answers, comments}
}

function createAnswer({user, body, score = 0, comments = []}) {
  return {user, body, score, comments}
}

function createComment({user, body}) {
  return {user, body}
}
